name: weather_app
description: A new Flutter project.


publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  dio: ^5.0.2
  wakelock: ^0.6.2
  flutter_screenutil: ^5.8.4
  url_launcher: ^6.1.11
  shared_preferences: ^2.2.0
  flutter_svg: ^2.0.7
  internet_connection_checker: ^1.0.0+1
  connectivity_plus: ^4.0.1
  equatable: ^2.0.5

  dartz: ^0.10.1
  flutter_bloc: ^8.1.2
  animate_do: ^3.0.2
  cached_network_image: ^3.2.3
  carousel_slider: ^4.2.1
  google_fonts: ^4.0.3
  shimmer: ^3.0.0

dev_dependencies:
  build_runner: ^2.3.3
  flutter_lints: ^2.0.0

  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true


